spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: otp
          uri: https://otpbank.hu
          predicates:
            - Path=/otp

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/